version: "3"
services:
  workspace:
    image: zzjcool/workspace
    container_name: workspace
    privileged: true
    ports:
      - "2222:2222"
    volumes:
      # 这里替换成需要挂载的目录
      - "/home/zheng:/root/host"
      - "host:/root"
    restart: unless-stopped

volumes:
  host: {}
